services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_register_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - user_register_network
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "cd /app && sleep 5 && diesel setup && diesel migration run"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - user_register_network
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: ["/bin/server"]

volumes:
  postgres_data:

networks:
  user_register_network:
    driver: bridge